import Head from "next/head";
import styles from "../styles/Home.module.css";
import { MeiliSearch } from "meilisearch";
import { useState } from "react";

export default function Home() {
  const [page, setPage] = useState(1);
  const [searchResults, setSearchResults] = useState([]);
  const [searchQuery, setSearchQuery] = useState({
    term: "",
    hitsPerPage: 8,
  });

  const client = new MeiliSearch({ host: "http://localhost:7700" });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Search your favorite movies</h1>
        <input
          className={styles.search}
          type="text"
          placeholder="Search for a movie..."
          onChange={(e) => {
            setSearchQuery({ ...searchQuery, term: e.target.value });
            client
              .index("movies")
              .search(searchQuery.term, {
                hitsPerPage: searchQuery.hitsPerPage,
              })
              .then((results) => {
                setSearchResults(results.hits);
              });
          }}
        />
        <div className={styles.grid}>
          {searchResults.map((resource) => (
            <div key={resource.title} className={styles.card}>
              <img
                src={resource.poster}
                alt={resource.name}
                width={200}
                height={300}
              />
              <h3>{resource.title} &rarr;</h3>
              <p>{resource.director}</p>
            </div>
          ))}
        </div>
        <button
          className={styles.button}
          onClick={async () => {
            setPage(page + 1);
            await client
              .index("movies")
              .search(searchQuery.term, {
                hitsPerPage: searchQuery.hitsPerPage,
                page: page,
              })
              .then((results) => {
                setSearchResults(results.hits);
              });
          }}
        >
          Load more
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          With love by Kenny
        </a>
      </footer>
    </div>
  );
}
